### ISSUE TITLE
Small things in amiritypewriter-0.4.zip

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/amiri-typewriter#2]
- [x] Please include a DSIG table, this is required for MS Word to recognise the font has OpenType features
- [x] Please hint the font with ttfautohint
- [x] Check if there is unused data at the end of the glyf table: glyf table may have unreachable data at the end of the table. Expected glyf table length 774 (from loca table), got length 32440 (difference: 31666)
- [x] In Bold, the full name is

```
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Amiri Typewriter
    </namerecord>
```

it should be 

```
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Amiri Typewriter Bold
    </namerecord>
```
- [x] name table item 10 is 

> Amiri Typewriter is an Arabic monowidth font inspired by the type of mechanical Arabic typewriters.

I suggest

> Amiri Typewriter is an Arabic monospaced font family inspired by the type of mechanical Arabic typewriters.
- [x] Copyright string must only contain ascii characters. I request settting it to

`Copyright 2012 The Amiri Typewriter Project Authors, with Reserved Font Name "Fira"`
-  [x] License string should be

`This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL`
- [x] post table should be type 2
- [x] the latin is missing some key punctuation characters:

```
$ pyfontaine --set "gwf_latin" AmiriTypewriter-Regular.ttf --missing;
              U+2013  –  EN DASH
              U+2014  —  EM DASH
              U+201a  ‚  SINGLE LOW-9 QUOTATION MARK
              U+201c  “  LEFT DOUBLE QUOTATION MARK
              U+201d  ”  RIGHT DOUBLE QUOTATION MARK
              U+201e  „  DOUBLE LOW-9 QUOTATION MARK
              U+2022  •  BULLET
              U+2039  ‹  SINGLE LEFT-POINTING ANGLE QUOTATION MARK
              U+203a  ›  SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
              U+20ac  €  EURO SIGN
              U+2074  ⁴  SUPERSCRIPT FOUR
              U+2215  ∕  DIVISION SLASH
```
- [x] Version in NAME id 5 string value must be 1.0 or higher
- [ ] Ideally the UPM is 1000, not 2048, to reduce filesize
- [x] Amiri Typewriter Bold has a `hmtx` value for `.notdef` of 68 that should be 0

**Comment by khaledhosny** [comment]
DSIG is needed only for “simple” scripts, Arabic will work regardless of its presence, do you want it because of the Latin part? Dropping glyph names is pyftsubset default, and I see no value in keeping them as the way the font is built makes them useless for PDF text extraction, and tools that really need glyph names (e.g. embedding the font in PDF) can just generate dummy glyph names (and they do AFAIK).

**Comment by khaledhosny** [comment]
I don’t see any thing suspicious about the glyph table, what tool gave you this warning?

**Comment by davelab6** [comment]
> I don’t see any thing suspicious about the glyph table, what tool gave you this warning?

fontbakery. It is probably buggy. 

> DSIG is needed only for “simple” scripts

OK cool

ttfautohint?

The UPM can be left as it is, and maybe refactor the font to 1000 in the future

**Comment by khaledhosny** [comment]
Haven’t tried ttfautohint with Arabic yet, so still trying to figure out where to start.

**Comment by davelab6** [comment]
It will help the Latin even if just defaults are used I think

On Saturday, 12 March 2016, Khaled Hosny notifications@github.com wrote:

> Haven’t tried ttfautohint with Arabic yet, so still trying to figure out
> where to start.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/khaledhosny/amiri-typewriter/issues/2#issuecomment-195807261
> .

## 

Cheers
Dave

**Comment by khaledhosny** [comment]
OK, authinted now. The 1000 UPM didn’t save much last I checked, but will look into it later.

**Comment by khaledhosny** [comment]
I’m keeping the existing UPM for now.
