### ISSUE TITLE
تداخل التنوين وعلامات التشكيل مع السطر الذي فوقها

### ISSUE THREAD

**Issue by OsamaAbbas** [khaledhosny/amiri-typewriter#6]
بالنظر إلى الصورة تتضح المشكلة عند كلمتي (خبيرًا طبيًّا ).

![image](https://user-images.githubusercontent.com/3346502/44582061-24178e00-a7db-11e8-901c-37191ca4391c.png)

البرنامج الظاهر في الأمام:
Pluma from the MATE Desktop

والبرنامج الآخر هو غوغل كروم.

**Comment by OsamaAbbas** [comment]
سبب وضعي لبرنامجين، هو أنه أحيانًا أجد مشكلات في الخط في البرامج البسيطة، مثل
gedit, xed, pluma
ولا أجدها في كروم أو فايرفوكس.

فالقصد إن المشكلة موجودة حتى مع محرك خطوط جيد مثل كروم.

**Comment by khaledhosny** [comment]
يفترض أن تكون الحال أفضل الآن، جرب وأخبرني بالنتيجة.

**Comment by OsamaAbbas** [comment]
نعم أفضل.
لكن أعتقد لو زدت ارتفاع السطر سيتحسن أكثر. حاليًّا فيه تلامس وإن كان بسيطًا
![image](https://user-images.githubusercontent.com/3346502/44793571-8e686e00-abe1-11e8-945f-883c12d6953d.png)
